[phases.setup]
nixPkgs = ["php82", "php82Packages.composer"]

[phases.build]
cmds = [
  "composer install --no-dev --optimize-autoloader --no-scripts",
  "mkdir -p members logs public/uploads",
  "chmod 755 members logs public/uploads"
]

[phases.start]
cmd = "php -S 0.0.0.0:$PORT -t ."

[variables]
PHP_VERSION = "8.2"